# Generated by Django 4.2.13 on 2024-06-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='instagram_accounts',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_subscribed',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_user_verified',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='membership_expiry',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_photo',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='verification_code',
        ),
    ]
