# Generated by Django 4.2.13 on 2024-06-09 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_instagram_accounts_remove_customuser_credit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=255)),
                ('template_content', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('scheduled_time', models.DateTimeField()),
                ('sent', models.BooleanField(default=False)),
                ('sent_time', models.DateTimeField(blank=True, null=True)),
                ('instagram_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auths.instagram_accounts')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('filed4', models.CharField(max_length=150)),
                ('filed1', models.CharField(max_length=150)),
                ('filed2', models.CharField(max_length=150)),
                ('filed3', models.CharField(max_length=150)),
                ('instagram_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auths.instagram_accounts')),
            ],
        ),
    ]
