# Generated by Django 4.2.13 on 2024-06-09 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0003_messagetemplate_message_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagram_accounts',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
